status = [
  "Build (ubuntu-latest, nightly)",
  "Build (macOS-latest, nightly)",
  "Format check (ubuntu-latest, nightly)",
  "Test (ubuntu-latest, nightly)",
  "Test (macOS-latest, nightly)",
  "KVM Tests",
]
delete_merged_branches = true
timeout_sec = 7200
