coverage:
  status:
    patch: off
    project: 
      default:
        target: auto   # Require same coverage ratio as base (from PR base or parent commit)
        # Allow a drop of 1%, to account for  fluctuations with regards to certain 
        # lines sometimes being present and missing, and sometimes not compiled at all
        threshold: 1% 
